<a href="https://colab.research.google.com/github/marsani/MachineLearning-2021/blob/main/praktikum01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world!!")

Hello world!!


In [ ]:
height=1.89
tall=True

In [ ]:
height

1.89

In [ ]:
tall

True

In [ ]:
'''list dapat Mengandung tipe data yg berbeda'''
[1.89,1.67,1.78,1.68,1.98]

[1.89, 1.67, 1.78, 1.68, 1.98]

In [ ]:
height = [1.84, 1.79, 1.82,1.90, 1.80]
height

[1.84, 1.79, 1.82, 1.9, 1.8]

In [ ]:
famz = ["Abe", 1.84, "Beb",1.79, "Cory", 1.82, "Dad", 1.90]
famz

['Abe', 1.84, 'Beb', 1.79, 'Cory', 1.82, 'Dad', 1.9]

In [ ]:
'''contoh'''
height = [1.84, 1.79, 1.82, 1.90, 1.80]
weight = [66.5, 60.3, 64.7, 89.5, 69.8] 

In [ ]:
height

[1.84, 1.79, 1.82, 1.9, 1.8]

In [ ]:
weight

[66.5, 60.3, 64.7, 89.5, 69.8]

In [ ]:
weight / height ** 2

TypeError: ignored

In [ ]:
'''numpy'''
import numpy as np
np_height = np.array(height)
np_height

array([1.84, 1.79, 1.82, 1.9 , 1.8 ])

In [ ]:
np_weight = np.array(weight)
np_weight

array([66.5, 60.3, 64.7, 89.5, 69.8])

In [ ]:
bmi = np_weight / np_height ** 2
bmi

array([19.64201323, 18.81963734, 19.53266514, 24.79224377, 21.54320988])

In [ ]:
np_height = np.array([1.84, 1.79,1.82, 1.9, 1.8])
np_weight = np.array([66.5, 60.3,64.7, 89.5, 69.8])

In [ ]:
'''ndarray = n-dimensional array'''
type(np_height)

numpy.ndarray

In [ ]:
type(np_weight)

numpy.ndarray

In [ ]:
np_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
np_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np_2d.shape

(2, 5)

Salah satu library untuk Machine Learning, yaitu numpy

In [ ]:
import numpy as np
np_height = np.array([1.84, 1.79,1.82, 1.9, 1.8])
np_weight = np.array([66.5, 60.3,64.7, 89.5, 69.8])

In [ ]:
type(np_height)

numpy.ndarray

In [ ]:
type(np_weight)

numpy.ndarray

In [ ]:
np_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
np_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np_2d.shape

(2, 5)

Libary Pandas

In [ ]:
import numpy as np
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
'''series'''
import pandas as pd 
import numpy as np 
data = pd.Series(['a','b','c','d']) 
data

0    a
1    b
2    c
3    d
dtype: object

In [ ]:
np1 = np.array(['a','b','c','d']) 
data_np = pd.Series(np1)
data_np

0    a
1    b
2    c
3    d
dtype: object

In [ ]:
import pandas as pd
Tab = pd.read_csv("/content/sample_data/Tab.csv")
Tab

Unnamed: 0     Negara  Populasi    Area    Ibukota
0         IN  Indonesia       250  123456    Jakarta
1         MA   Malaysia        25    3456         KL
2         SI  Singapura        15     456  Singapura
3         JP     Jepang        60    5678      Tokyo
4         TH   Thailand        45     678    Bangkok